[versions]
agp = "8.2.2"
kotlin = "1.7.21"
appcompat = "1.6.1"
autodispose-android-archcomponents = "1.3.0"
conductor = "2.1.5"
constraintlayout = "1.1.3"
dagger = "2.18"
datashare = "1.3.0"
documentfile = "1.0.1"
emoji2-bundled = "1.4.0"
exifinterface = "1.0.0"
exoplayer-core = "r2.9.0"
flexbox-layout = "0.3.1"
glide = "4.16.0"
javax-annotation-api = "1.3.2"
jdk9-deps = "1ffe84c468"
junit = "4.12"
kotlin-stdlib = "1.7.21"
kotlinx-coroutines-core = "1.4.3"
ktx = "1.1.0"
libphonenumber-android = "8.13.47"
lifecycle-extensions = "2.1.0"
material = "1.0.0"
mockito-android = "2.18.3"
moshi = "1.8.0"
okhttp = "2.5.0"
okhttp-version = "4.10.0"
photoview = "2.1.4"
realm-android-adapters = "3.1.0"
realm-annotations = "10.15.0"
runner = "1.1.0-alpha3"
rx-preferences = "2.0.0-RC3"
rxandroid = "2.0.1"
rxbinding-kotlin = "2.0.0"
rxdogtag = "0.2.0"
rxjava = "2.1.4"
rxkotlin = "2.1.0"
shortcutbadger = "1.1.22"
timber = "5.0.1"
google-services = "4.3.14"
viewpager2 = "1.0.0-beta05"
work-runtime-ktx = "2.8.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfile" }
androidx-emoji2-bundled = { module = "androidx.emoji2:emoji2-bundled", version.ref = "emoji2-bundled" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "exifinterface" }
androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }
androidx-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle-extensions" }
androidx-lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycle-extensions" }
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work-runtime-ktx" }
androidx-work-rxjava2 = { module = "androidx.work:work-rxjava2", version.ref = "work-runtime-ktx" }
autodispose = { module = "com.uber.autodispose:autodispose", version.ref = "autodispose-android-archcomponents" }
autodispose-android = { module = "com.uber.autodispose:autodispose-android", version.ref = "autodispose-android-archcomponents" }
autodispose-android-archcomponents = { module = "com.uber.autodispose:autodispose-android-archcomponents", version.ref = "autodispose-android-archcomponents" }
autodispose-android-archcomponents-test = { module = "com.uber.autodispose:autodispose-android-archcomponents-test", version.ref = "autodispose-android-archcomponents" }
autodispose-lifecycle = { module = "com.uber.autodispose:autodispose-lifecycle", version.ref = "autodispose-android-archcomponents" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
conductor = { module = "com.bluelinelabs:conductor", version.ref = "conductor" }
conductor-archlifecycle = { module = "com.bluelinelabs:conductor-archlifecycle", version.ref = "conductor" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-android-processor = { module = "com.google.dagger:dagger-android-processor", version.ref = "dagger" }
dagger-android-support = { module = "com.google.dagger:dagger-android-support", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
datashare = { module = "com.callcontrol:datashare", version.ref = "datashare" }
exoplayer-core = { module = "com.github.google.ExoPlayer:exoplayer-core", version.ref = "exoplayer-core" }
flexbox-layout = { module = "com.github.google:flexbox-layout", version.ref = "flexbox-layout" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
javax-annotation-api = { module = "javax.annotation:javax.annotation-api", version.ref = "javax-annotation-api" }
jdk9-deps = { module = "com.github.pengrad:jdk9-deps", version.ref = "jdk9-deps" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin-stdlib" }
kotlin-stdlib-jdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin-stdlib" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-core" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }
kotlinx-coroutines-reactive = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactive", version.ref = "kotlinx-coroutines-core" }
kotlinx-coroutines-rx2 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-rx2", version.ref = "kotlinx-coroutines-core" }
libphonenumber-android = { module = "io.michaelrocks:libphonenumber-android", version.ref = "libphonenumber-android" }
material = { module = "com.google.android.material:material", version.ref = "material" }
mockito-android = { module = "org.mockito:mockito-android", version.ref = "mockito-android" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito-android" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
okhttp = { module = "com.squareup.okhttp:okhttp", version.ref = "okhttp" }
okhttp-urlconnection = { module = "com.squareup.okhttp:okhttp-urlconnection", version.ref = "okhttp" }
okhttp3-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp-version" }
photoview = { module = "com.github.chrisbanes:photoview", version.ref = "photoview" }
realm-android-adapters = { module = "com.github.realm:realm-android-adapters", version.ref = "realm-android-adapters" }
realm-annotations = { module = "io.realm:realm-annotations", version.ref = "realm-annotations" }
realm-annotations-processor = { module = "io.realm:realm-annotations-processor", version.ref = "realm-annotations" }
rx-preferences = { module = "com.f2prateek.rx.preferences2:rx-preferences", version.ref = "rx-preferences" }
rxandroid = { module = "io.reactivex.rxjava2:rxandroid", version.ref = "rxandroid" }
rxbinding-kotlin = { module = "com.jakewharton.rxbinding2:rxbinding-kotlin", version.ref = "rxbinding-kotlin" }
rxbinding-support-v4-kotlin = { module = "com.jakewharton.rxbinding2:rxbinding-support-v4-kotlin", version.ref = "rxbinding-kotlin" }
rxdogtag = { module = "com.uber.rxdogtag:rxdogtag", version.ref = "rxdogtag" }
rxdogtag-autodispose = { module = "com.uber.rxdogtag:rxdogtag-autodispose", version.ref = "rxdogtag" }
rxjava = { module = "io.reactivex.rxjava2:rxjava", version.ref = "rxjava" }
rxkotlin = { module = "io.reactivex.rxjava2:rxkotlin", version.ref = "rxkotlin" }
shortcutbadger = { module = "me.leolin:ShortcutBadger", version.ref = "shortcutbadger" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
